version: '3.1'

services:

  nginx:
    build: .
    ports:
      - "8146:8146"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña_segura
      MYSQL_DATABASE: Cine
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"

volumes:
  db_data:


